export const realms = [
  {
    id: "artisan",
    title: "The Artisan Sphere",
    description: "Paintings, sketches, and visual artistry.",
    href: "/artisan",
    gradient: "from-orange-500/20 to-yellow-500/20",
    border: "border-orange-400/30",
    glow: "group-hover:shadow-orange-500/20",
  },
  {
    id: "verse",
    title: "The Verse Sanctuary",
    description: "Poetry, emotions, and lyrical expression.",
    href: "/verse",
    gradient: "from-violet-500/20 to-purple-700/20",
    border: "border-violet-400/30",
    glow: "group-hover:shadow-violet-500/20",
  },
  {
    id: "otaku",
    title: "The Otaku Dimension",
    description: "Anime culture, fandoms, and imagination.",
    href: "/otaku",
    gradient: "from-cyan-500/20 to-blue-700/20",
    border: "border-cyan-400/30",
    glow: "group-hover:shadow-cyan-500/20",
  },
  {
    id: "literary",
    title: "The Literary Dominion",
    description: "Novels, stories, and immersive worlds.",
    href: "/literary",
    gradient: "from-amber-500/20 to-red-700/20",
    border: "border-amber-400/30",
    glow: "group-hover:shadow-amber-500/20",
  },
  {
    id: "manga",
    title: "The Manga Nexus",
    description: "Manga panels, arcs, and legendary journeys.",
    href: "/manga",
    gradient: "from-zinc-500/20 to-neutral-700/20",
    border: "border-zinc-400/30",
    glow: "group-hover:shadow-zinc-500/20",
  },
  {
    id: "creative",
    title: "The Creative Realm",
    description: "Crafts, creativity, and handmade expression.",
    href: "/creative",
    gradient: "from-pink-500/20 to-rose-700/20",
    border: "border-pink-400/30",
    glow: "group-hover:shadow-pink-500/20",
  },
] as const;